apiVersion: apps/v1
kind: Deployment
metadata:
  name: qos-controller
  namespace: default
  labels:
    app: qos-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qos-controller
  template:
    metadata:
      labels:
        app: qos-controller
    spec:
      serviceAccountName: go-controller-sa
      containers:
      - name: qos-controller
        image: dejanualex/go-controller:1.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
 