apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-controller
  namespace: default
  labels:
    app: go-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-controller
  template:
    metadata:
      labels:
        app: go-controller
    spec:
      serviceAccountName: go-controller-sa
      containers:
      - name: go-controller
        image: alexdejanu/go-controller:1.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
 